version: '3.8'

services:
  database:
    container_name: database_symfony_test
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: symfony_test
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php_symfony_test
    build:
      context: ./php8.1
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www
    depends_on:
      - database

  nginx:
    container_name: nginx_symfony_test
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  maildev:
    image: maildev/maildev
    container_name: maildev_symfony_test
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_symfony_test
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: 64M